kind: Service
apiVersion: v1
metadata:
  name: consentapidemo1
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: consentapidemo1
  clusterIP: 10.0.203.245
  clusterIPs:
    - 10.0.203.245
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
